# -----------------------***-----------------------
# @author: SiberianHusky
# @data: 2024-5-21
# -----------------------***-----------------------

version: '${project.version}'
raceMap:
  name: 'test'