name: RaceCore
version: '${project.version}'
main: online.yudream.racecore.RaceCore
author: SiberianHusky
api-version: '1.20'
commands:
  RaceCoreAdmin:
    aliases: rca
    usage: /rca help
  RaceCore:
    aliases: rc
    usage: /rc help