# -----------------------***-----------------------
# @author: SiberianHusky
# @data: 2024-5-21
# -----------------------***-----------------------

version: '1.0-SNAPSHOT'
raceMap:
  name: 'test'
minStartPlayer: 4