name: RaceCore
version: '1.0-SNAPSHOT'
main: online.yudream.racecore.RaceCore
author: SiberianHusky
api-version: '1.20'
commands:
  RaceCoreAdmin:
    aliases: rca
    usage: /rca help
    permission: racecore.admin
  RaceCore:
    aliases: rc
    usage: /rc help